/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutProfileImport } from './routes/_layout/profile'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutStoreIndexImport } from './routes/_layout/store/index'
import { Route as LayoutSettingsIndexImport } from './routes/_layout/settings/index'
import { Route as LayoutSalesIndexImport } from './routes/_layout/sales/index'
import { Route as LayoutReportsIndexImport } from './routes/_layout/reports/index'
import { Route as LayoutFinancesIndexImport } from './routes/_layout/finances/index'
import { Route as LayoutExpensesIndexImport } from './routes/_layout/expenses/index'
import { Route as LayoutEmployeesIndexImport } from './routes/_layout/employees/index'
import { Route as LayoutSettingsPrintTypesImport } from './routes/_layout/settings/print-types'
import { Route as LayoutSettingsPaymentTypesImport } from './routes/_layout/settings/payment-types'
import { Route as LayoutSettingsExpenseTypesImport } from './routes/_layout/settings/expense-types'
import { Route as LayoutSalesSalesProductImport } from './routes/_layout/sales/sales-product'
import { Route as LayoutSalesProductsImport } from './routes/_layout/sales/products'
import { Route as LayoutReportsWriteOffProductsImport } from './routes/_layout/reports/write-off-products'
import { Route as LayoutReportsSuppliersImport } from './routes/_layout/reports/suppliers'
import { Route as LayoutReportsSalesProductsImport } from './routes/_layout/reports/sales-products'
import { Route as LayoutReportsExpensesImport } from './routes/_layout/reports/expenses'
import { Route as LayoutReportsDebtorsImport } from './routes/_layout/reports/debtors'
import { Route as LayoutFinancesWriteOffProductsImport } from './routes/_layout/finances/write-off-products'
import { Route as LayoutFinancesSaleProductsImport } from './routes/_layout/finances/sale-products'
import { Route as LayoutFinancesExpensesImport } from './routes/_layout/finances/expenses'
import { Route as LayoutFinancesComingProductsImport } from './routes/_layout/finances/coming-products'
import { Route as LayoutExpensesWriteOffProductsImport } from './routes/_layout/expenses/write-off-products'
import { Route as LayoutExpensesProfitLoseImport } from './routes/_layout/expenses/profit-lose'
import { Route as LayoutExpensesListImport } from './routes/_layout/expenses/list'
import { Route as LayoutExpensesCashFlowImport } from './routes/_layout/expenses/cash-flow'
import { Route as LayoutEmployeesUsersImport } from './routes/_layout/employees/users'
import { Route as LayoutStoreProductsIndexImport } from './routes/_layout/store/products/index'
import { Route as LayoutStoreProductsIdImport } from './routes/_layout/store/products/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreIndexRoute = LayoutStoreIndexImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsIndexRoute = LayoutSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesIndexRoute = LayoutSalesIndexImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsIndexRoute = LayoutReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFinancesIndexRoute = LayoutFinancesIndexImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExpensesIndexRoute = LayoutExpensesIndexImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEmployeesIndexRoute = LayoutEmployeesIndexImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsPrintTypesRoute = LayoutSettingsPrintTypesImport.update({
  id: '/settings/print-types',
  path: '/settings/print-types',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsPaymentTypesRoute = LayoutSettingsPaymentTypesImport.update(
  {
    id: '/settings/payment-types',
    path: '/settings/payment-types',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSettingsExpenseTypesRoute = LayoutSettingsExpenseTypesImport.update(
  {
    id: '/settings/expense-types',
    path: '/settings/expense-types',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSalesSalesProductRoute = LayoutSalesSalesProductImport.update({
  id: '/sales/sales-product',
  path: '/sales/sales-product',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesProductsRoute = LayoutSalesProductsImport.update({
  id: '/sales/products',
  path: '/sales/products',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsWriteOffProductsRoute =
  LayoutReportsWriteOffProductsImport.update({
    id: '/reports/write-off-products',
    path: '/reports/write-off-products',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutReportsSuppliersRoute = LayoutReportsSuppliersImport.update({
  id: '/reports/suppliers',
  path: '/reports/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsSalesProductsRoute = LayoutReportsSalesProductsImport.update(
  {
    id: '/reports/sales-products',
    path: '/reports/sales-products',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutReportsExpensesRoute = LayoutReportsExpensesImport.update({
  id: '/reports/expenses',
  path: '/reports/expenses',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsDebtorsRoute = LayoutReportsDebtorsImport.update({
  id: '/reports/debtors',
  path: '/reports/debtors',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFinancesWriteOffProductsRoute =
  LayoutFinancesWriteOffProductsImport.update({
    id: '/finances/write-off-products',
    path: '/finances/write-off-products',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutFinancesSaleProductsRoute = LayoutFinancesSaleProductsImport.update(
  {
    id: '/finances/sale-products',
    path: '/finances/sale-products',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutFinancesExpensesRoute = LayoutFinancesExpensesImport.update({
  id: '/finances/expenses',
  path: '/finances/expenses',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFinancesComingProductsRoute =
  LayoutFinancesComingProductsImport.update({
    id: '/finances/coming-products',
    path: '/finances/coming-products',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutExpensesWriteOffProductsRoute =
  LayoutExpensesWriteOffProductsImport.update({
    id: '/expenses/write-off-products',
    path: '/expenses/write-off-products',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutExpensesProfitLoseRoute = LayoutExpensesProfitLoseImport.update({
  id: '/expenses/profit-lose',
  path: '/expenses/profit-lose',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExpensesListRoute = LayoutExpensesListImport.update({
  id: '/expenses/list',
  path: '/expenses/list',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExpensesCashFlowRoute = LayoutExpensesCashFlowImport.update({
  id: '/expenses/cash-flow',
  path: '/expenses/cash-flow',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEmployeesUsersRoute = LayoutEmployeesUsersImport.update({
  id: '/employees/users',
  path: '/employees/users',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreProductsIndexRoute = LayoutStoreProductsIndexImport.update({
  id: '/store/products/',
  path: '/store/products/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreProductsIdRoute = LayoutStoreProductsIdImport.update({
  id: '/store/products/$id',
  path: '/store/products/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/employees/users': {
      id: '/_layout/employees/users'
      path: '/employees/users'
      fullPath: '/employees/users'
      preLoaderRoute: typeof LayoutEmployeesUsersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/expenses/cash-flow': {
      id: '/_layout/expenses/cash-flow'
      path: '/expenses/cash-flow'
      fullPath: '/expenses/cash-flow'
      preLoaderRoute: typeof LayoutExpensesCashFlowImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/expenses/list': {
      id: '/_layout/expenses/list'
      path: '/expenses/list'
      fullPath: '/expenses/list'
      preLoaderRoute: typeof LayoutExpensesListImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/expenses/profit-lose': {
      id: '/_layout/expenses/profit-lose'
      path: '/expenses/profit-lose'
      fullPath: '/expenses/profit-lose'
      preLoaderRoute: typeof LayoutExpensesProfitLoseImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/expenses/write-off-products': {
      id: '/_layout/expenses/write-off-products'
      path: '/expenses/write-off-products'
      fullPath: '/expenses/write-off-products'
      preLoaderRoute: typeof LayoutExpensesWriteOffProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finances/coming-products': {
      id: '/_layout/finances/coming-products'
      path: '/finances/coming-products'
      fullPath: '/finances/coming-products'
      preLoaderRoute: typeof LayoutFinancesComingProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finances/expenses': {
      id: '/_layout/finances/expenses'
      path: '/finances/expenses'
      fullPath: '/finances/expenses'
      preLoaderRoute: typeof LayoutFinancesExpensesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finances/sale-products': {
      id: '/_layout/finances/sale-products'
      path: '/finances/sale-products'
      fullPath: '/finances/sale-products'
      preLoaderRoute: typeof LayoutFinancesSaleProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finances/write-off-products': {
      id: '/_layout/finances/write-off-products'
      path: '/finances/write-off-products'
      fullPath: '/finances/write-off-products'
      preLoaderRoute: typeof LayoutFinancesWriteOffProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/debtors': {
      id: '/_layout/reports/debtors'
      path: '/reports/debtors'
      fullPath: '/reports/debtors'
      preLoaderRoute: typeof LayoutReportsDebtorsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/expenses': {
      id: '/_layout/reports/expenses'
      path: '/reports/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof LayoutReportsExpensesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/sales-products': {
      id: '/_layout/reports/sales-products'
      path: '/reports/sales-products'
      fullPath: '/reports/sales-products'
      preLoaderRoute: typeof LayoutReportsSalesProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/suppliers': {
      id: '/_layout/reports/suppliers'
      path: '/reports/suppliers'
      fullPath: '/reports/suppliers'
      preLoaderRoute: typeof LayoutReportsSuppliersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/write-off-products': {
      id: '/_layout/reports/write-off-products'
      path: '/reports/write-off-products'
      fullPath: '/reports/write-off-products'
      preLoaderRoute: typeof LayoutReportsWriteOffProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/products': {
      id: '/_layout/sales/products'
      path: '/sales/products'
      fullPath: '/sales/products'
      preLoaderRoute: typeof LayoutSalesProductsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/sales-product': {
      id: '/_layout/sales/sales-product'
      path: '/sales/sales-product'
      fullPath: '/sales/sales-product'
      preLoaderRoute: typeof LayoutSalesSalesProductImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings/expense-types': {
      id: '/_layout/settings/expense-types'
      path: '/settings/expense-types'
      fullPath: '/settings/expense-types'
      preLoaderRoute: typeof LayoutSettingsExpenseTypesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings/payment-types': {
      id: '/_layout/settings/payment-types'
      path: '/settings/payment-types'
      fullPath: '/settings/payment-types'
      preLoaderRoute: typeof LayoutSettingsPaymentTypesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings/print-types': {
      id: '/_layout/settings/print-types'
      path: '/settings/print-types'
      fullPath: '/settings/print-types'
      preLoaderRoute: typeof LayoutSettingsPrintTypesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/employees/': {
      id: '/_layout/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof LayoutEmployeesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/expenses/': {
      id: '/_layout/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof LayoutExpensesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finances/': {
      id: '/_layout/finances/'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof LayoutFinancesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports/': {
      id: '/_layout/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/': {
      id: '/_layout/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/': {
      id: '/_layout/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof LayoutStoreIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/products/$id': {
      id: '/_layout/store/products/$id'
      path: '/store/products/$id'
      fullPath: '/store/products/$id'
      preLoaderRoute: typeof LayoutStoreProductsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/products/': {
      id: '/_layout/store/products/'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof LayoutStoreProductsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEmployeesUsersRoute: typeof LayoutEmployeesUsersRoute
  LayoutExpensesCashFlowRoute: typeof LayoutExpensesCashFlowRoute
  LayoutExpensesListRoute: typeof LayoutExpensesListRoute
  LayoutExpensesProfitLoseRoute: typeof LayoutExpensesProfitLoseRoute
  LayoutExpensesWriteOffProductsRoute: typeof LayoutExpensesWriteOffProductsRoute
  LayoutFinancesComingProductsRoute: typeof LayoutFinancesComingProductsRoute
  LayoutFinancesExpensesRoute: typeof LayoutFinancesExpensesRoute
  LayoutFinancesSaleProductsRoute: typeof LayoutFinancesSaleProductsRoute
  LayoutFinancesWriteOffProductsRoute: typeof LayoutFinancesWriteOffProductsRoute
  LayoutReportsDebtorsRoute: typeof LayoutReportsDebtorsRoute
  LayoutReportsExpensesRoute: typeof LayoutReportsExpensesRoute
  LayoutReportsSalesProductsRoute: typeof LayoutReportsSalesProductsRoute
  LayoutReportsSuppliersRoute: typeof LayoutReportsSuppliersRoute
  LayoutReportsWriteOffProductsRoute: typeof LayoutReportsWriteOffProductsRoute
  LayoutSalesProductsRoute: typeof LayoutSalesProductsRoute
  LayoutSalesSalesProductRoute: typeof LayoutSalesSalesProductRoute
  LayoutSettingsExpenseTypesRoute: typeof LayoutSettingsExpenseTypesRoute
  LayoutSettingsPaymentTypesRoute: typeof LayoutSettingsPaymentTypesRoute
  LayoutSettingsPrintTypesRoute: typeof LayoutSettingsPrintTypesRoute
  LayoutEmployeesIndexRoute: typeof LayoutEmployeesIndexRoute
  LayoutExpensesIndexRoute: typeof LayoutExpensesIndexRoute
  LayoutFinancesIndexRoute: typeof LayoutFinancesIndexRoute
  LayoutReportsIndexRoute: typeof LayoutReportsIndexRoute
  LayoutSalesIndexRoute: typeof LayoutSalesIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutStoreIndexRoute: typeof LayoutStoreIndexRoute
  LayoutStoreProductsIdRoute: typeof LayoutStoreProductsIdRoute
  LayoutStoreProductsIndexRoute: typeof LayoutStoreProductsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEmployeesUsersRoute: LayoutEmployeesUsersRoute,
  LayoutExpensesCashFlowRoute: LayoutExpensesCashFlowRoute,
  LayoutExpensesListRoute: LayoutExpensesListRoute,
  LayoutExpensesProfitLoseRoute: LayoutExpensesProfitLoseRoute,
  LayoutExpensesWriteOffProductsRoute: LayoutExpensesWriteOffProductsRoute,
  LayoutFinancesComingProductsRoute: LayoutFinancesComingProductsRoute,
  LayoutFinancesExpensesRoute: LayoutFinancesExpensesRoute,
  LayoutFinancesSaleProductsRoute: LayoutFinancesSaleProductsRoute,
  LayoutFinancesWriteOffProductsRoute: LayoutFinancesWriteOffProductsRoute,
  LayoutReportsDebtorsRoute: LayoutReportsDebtorsRoute,
  LayoutReportsExpensesRoute: LayoutReportsExpensesRoute,
  LayoutReportsSalesProductsRoute: LayoutReportsSalesProductsRoute,
  LayoutReportsSuppliersRoute: LayoutReportsSuppliersRoute,
  LayoutReportsWriteOffProductsRoute: LayoutReportsWriteOffProductsRoute,
  LayoutSalesProductsRoute: LayoutSalesProductsRoute,
  LayoutSalesSalesProductRoute: LayoutSalesSalesProductRoute,
  LayoutSettingsExpenseTypesRoute: LayoutSettingsExpenseTypesRoute,
  LayoutSettingsPaymentTypesRoute: LayoutSettingsPaymentTypesRoute,
  LayoutSettingsPrintTypesRoute: LayoutSettingsPrintTypesRoute,
  LayoutEmployeesIndexRoute: LayoutEmployeesIndexRoute,
  LayoutExpensesIndexRoute: LayoutExpensesIndexRoute,
  LayoutFinancesIndexRoute: LayoutFinancesIndexRoute,
  LayoutReportsIndexRoute: LayoutReportsIndexRoute,
  LayoutSalesIndexRoute: LayoutSalesIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutStoreIndexRoute: LayoutStoreIndexRoute,
  LayoutStoreProductsIdRoute: LayoutStoreProductsIdRoute,
  LayoutStoreProductsIndexRoute: LayoutStoreProductsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/employees/users': typeof LayoutEmployeesUsersRoute
  '/expenses/cash-flow': typeof LayoutExpensesCashFlowRoute
  '/expenses/list': typeof LayoutExpensesListRoute
  '/expenses/profit-lose': typeof LayoutExpensesProfitLoseRoute
  '/expenses/write-off-products': typeof LayoutExpensesWriteOffProductsRoute
  '/finances/coming-products': typeof LayoutFinancesComingProductsRoute
  '/finances/expenses': typeof LayoutFinancesExpensesRoute
  '/finances/sale-products': typeof LayoutFinancesSaleProductsRoute
  '/finances/write-off-products': typeof LayoutFinancesWriteOffProductsRoute
  '/reports/debtors': typeof LayoutReportsDebtorsRoute
  '/reports/expenses': typeof LayoutReportsExpensesRoute
  '/reports/sales-products': typeof LayoutReportsSalesProductsRoute
  '/reports/suppliers': typeof LayoutReportsSuppliersRoute
  '/reports/write-off-products': typeof LayoutReportsWriteOffProductsRoute
  '/sales/products': typeof LayoutSalesProductsRoute
  '/sales/sales-product': typeof LayoutSalesSalesProductRoute
  '/settings/expense-types': typeof LayoutSettingsExpenseTypesRoute
  '/settings/payment-types': typeof LayoutSettingsPaymentTypesRoute
  '/settings/print-types': typeof LayoutSettingsPrintTypesRoute
  '/employees': typeof LayoutEmployeesIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/finances': typeof LayoutFinancesIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/sales': typeof LayoutSalesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/store': typeof LayoutStoreIndexRoute
  '/store/products/$id': typeof LayoutStoreProductsIdRoute
  '/store/products': typeof LayoutStoreProductsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/employees/users': typeof LayoutEmployeesUsersRoute
  '/expenses/cash-flow': typeof LayoutExpensesCashFlowRoute
  '/expenses/list': typeof LayoutExpensesListRoute
  '/expenses/profit-lose': typeof LayoutExpensesProfitLoseRoute
  '/expenses/write-off-products': typeof LayoutExpensesWriteOffProductsRoute
  '/finances/coming-products': typeof LayoutFinancesComingProductsRoute
  '/finances/expenses': typeof LayoutFinancesExpensesRoute
  '/finances/sale-products': typeof LayoutFinancesSaleProductsRoute
  '/finances/write-off-products': typeof LayoutFinancesWriteOffProductsRoute
  '/reports/debtors': typeof LayoutReportsDebtorsRoute
  '/reports/expenses': typeof LayoutReportsExpensesRoute
  '/reports/sales-products': typeof LayoutReportsSalesProductsRoute
  '/reports/suppliers': typeof LayoutReportsSuppliersRoute
  '/reports/write-off-products': typeof LayoutReportsWriteOffProductsRoute
  '/sales/products': typeof LayoutSalesProductsRoute
  '/sales/sales-product': typeof LayoutSalesSalesProductRoute
  '/settings/expense-types': typeof LayoutSettingsExpenseTypesRoute
  '/settings/payment-types': typeof LayoutSettingsPaymentTypesRoute
  '/settings/print-types': typeof LayoutSettingsPrintTypesRoute
  '/employees': typeof LayoutEmployeesIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/finances': typeof LayoutFinancesIndexRoute
  '/reports': typeof LayoutReportsIndexRoute
  '/sales': typeof LayoutSalesIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/store': typeof LayoutStoreIndexRoute
  '/store/products/$id': typeof LayoutStoreProductsIdRoute
  '/store/products': typeof LayoutStoreProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/employees/users': typeof LayoutEmployeesUsersRoute
  '/_layout/expenses/cash-flow': typeof LayoutExpensesCashFlowRoute
  '/_layout/expenses/list': typeof LayoutExpensesListRoute
  '/_layout/expenses/profit-lose': typeof LayoutExpensesProfitLoseRoute
  '/_layout/expenses/write-off-products': typeof LayoutExpensesWriteOffProductsRoute
  '/_layout/finances/coming-products': typeof LayoutFinancesComingProductsRoute
  '/_layout/finances/expenses': typeof LayoutFinancesExpensesRoute
  '/_layout/finances/sale-products': typeof LayoutFinancesSaleProductsRoute
  '/_layout/finances/write-off-products': typeof LayoutFinancesWriteOffProductsRoute
  '/_layout/reports/debtors': typeof LayoutReportsDebtorsRoute
  '/_layout/reports/expenses': typeof LayoutReportsExpensesRoute
  '/_layout/reports/sales-products': typeof LayoutReportsSalesProductsRoute
  '/_layout/reports/suppliers': typeof LayoutReportsSuppliersRoute
  '/_layout/reports/write-off-products': typeof LayoutReportsWriteOffProductsRoute
  '/_layout/sales/products': typeof LayoutSalesProductsRoute
  '/_layout/sales/sales-product': typeof LayoutSalesSalesProductRoute
  '/_layout/settings/expense-types': typeof LayoutSettingsExpenseTypesRoute
  '/_layout/settings/payment-types': typeof LayoutSettingsPaymentTypesRoute
  '/_layout/settings/print-types': typeof LayoutSettingsPrintTypesRoute
  '/_layout/employees/': typeof LayoutEmployeesIndexRoute
  '/_layout/expenses/': typeof LayoutExpensesIndexRoute
  '/_layout/finances/': typeof LayoutFinancesIndexRoute
  '/_layout/reports/': typeof LayoutReportsIndexRoute
  '/_layout/sales/': typeof LayoutSalesIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/store/': typeof LayoutStoreIndexRoute
  '/_layout/store/products/$id': typeof LayoutStoreProductsIdRoute
  '/_layout/store/products/': typeof LayoutStoreProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/'
    | '/employees/users'
    | '/expenses/cash-flow'
    | '/expenses/list'
    | '/expenses/profit-lose'
    | '/expenses/write-off-products'
    | '/finances/coming-products'
    | '/finances/expenses'
    | '/finances/sale-products'
    | '/finances/write-off-products'
    | '/reports/debtors'
    | '/reports/expenses'
    | '/reports/sales-products'
    | '/reports/suppliers'
    | '/reports/write-off-products'
    | '/sales/products'
    | '/sales/sales-product'
    | '/settings/expense-types'
    | '/settings/payment-types'
    | '/settings/print-types'
    | '/employees'
    | '/expenses'
    | '/finances'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/store'
    | '/store/products/$id'
    | '/store/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/'
    | '/employees/users'
    | '/expenses/cash-flow'
    | '/expenses/list'
    | '/expenses/profit-lose'
    | '/expenses/write-off-products'
    | '/finances/coming-products'
    | '/finances/expenses'
    | '/finances/sale-products'
    | '/finances/write-off-products'
    | '/reports/debtors'
    | '/reports/expenses'
    | '/reports/sales-products'
    | '/reports/suppliers'
    | '/reports/write-off-products'
    | '/sales/products'
    | '/sales/sales-product'
    | '/settings/expense-types'
    | '/settings/payment-types'
    | '/settings/print-types'
    | '/employees'
    | '/expenses'
    | '/finances'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/store'
    | '/store/products/$id'
    | '/store/products'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/profile'
    | '/_layout/'
    | '/_layout/employees/users'
    | '/_layout/expenses/cash-flow'
    | '/_layout/expenses/list'
    | '/_layout/expenses/profit-lose'
    | '/_layout/expenses/write-off-products'
    | '/_layout/finances/coming-products'
    | '/_layout/finances/expenses'
    | '/_layout/finances/sale-products'
    | '/_layout/finances/write-off-products'
    | '/_layout/reports/debtors'
    | '/_layout/reports/expenses'
    | '/_layout/reports/sales-products'
    | '/_layout/reports/suppliers'
    | '/_layout/reports/write-off-products'
    | '/_layout/sales/products'
    | '/_layout/sales/sales-product'
    | '/_layout/settings/expense-types'
    | '/_layout/settings/payment-types'
    | '/_layout/settings/print-types'
    | '/_layout/employees/'
    | '/_layout/expenses/'
    | '/_layout/finances/'
    | '/_layout/reports/'
    | '/_layout/sales/'
    | '/_layout/settings/'
    | '/_layout/store/'
    | '/_layout/store/products/$id'
    | '/_layout/store/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard",
        "/_layout/profile",
        "/_layout/",
        "/_layout/employees/users",
        "/_layout/expenses/cash-flow",
        "/_layout/expenses/list",
        "/_layout/expenses/profit-lose",
        "/_layout/expenses/write-off-products",
        "/_layout/finances/coming-products",
        "/_layout/finances/expenses",
        "/_layout/finances/sale-products",
        "/_layout/finances/write-off-products",
        "/_layout/reports/debtors",
        "/_layout/reports/expenses",
        "/_layout/reports/sales-products",
        "/_layout/reports/suppliers",
        "/_layout/reports/write-off-products",
        "/_layout/sales/products",
        "/_layout/sales/sales-product",
        "/_layout/settings/expense-types",
        "/_layout/settings/payment-types",
        "/_layout/settings/print-types",
        "/_layout/employees/",
        "/_layout/expenses/",
        "/_layout/finances/",
        "/_layout/reports/",
        "/_layout/sales/",
        "/_layout/settings/",
        "/_layout/store/",
        "/_layout/store/products/$id",
        "/_layout/store/products/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile": {
      "filePath": "_layout/profile.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/employees/users": {
      "filePath": "_layout/employees/users.tsx",
      "parent": "/_layout"
    },
    "/_layout/expenses/cash-flow": {
      "filePath": "_layout/expenses/cash-flow.tsx",
      "parent": "/_layout"
    },
    "/_layout/expenses/list": {
      "filePath": "_layout/expenses/list.tsx",
      "parent": "/_layout"
    },
    "/_layout/expenses/profit-lose": {
      "filePath": "_layout/expenses/profit-lose.tsx",
      "parent": "/_layout"
    },
    "/_layout/expenses/write-off-products": {
      "filePath": "_layout/expenses/write-off-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/finances/coming-products": {
      "filePath": "_layout/finances/coming-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/finances/expenses": {
      "filePath": "_layout/finances/expenses.tsx",
      "parent": "/_layout"
    },
    "/_layout/finances/sale-products": {
      "filePath": "_layout/finances/sale-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/finances/write-off-products": {
      "filePath": "_layout/finances/write-off-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/debtors": {
      "filePath": "_layout/reports/debtors.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/expenses": {
      "filePath": "_layout/reports/expenses.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/sales-products": {
      "filePath": "_layout/reports/sales-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/suppliers": {
      "filePath": "_layout/reports/suppliers.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/write-off-products": {
      "filePath": "_layout/reports/write-off-products.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales/products": {
      "filePath": "_layout/sales/products.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales/sales-product": {
      "filePath": "_layout/sales/sales-product.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings/expense-types": {
      "filePath": "_layout/settings/expense-types.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings/payment-types": {
      "filePath": "_layout/settings/payment-types.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings/print-types": {
      "filePath": "_layout/settings/print-types.tsx",
      "parent": "/_layout"
    },
    "/_layout/employees/": {
      "filePath": "_layout/employees/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/expenses/": {
      "filePath": "_layout/expenses/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/finances/": {
      "filePath": "_layout/finances/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/reports/": {
      "filePath": "_layout/reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales/": {
      "filePath": "_layout/sales/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings/": {
      "filePath": "_layout/settings/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/store/": {
      "filePath": "_layout/store/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/store/products/$id": {
      "filePath": "_layout/store/products/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/store/products/": {
      "filePath": "_layout/store/products/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
